### ISSUE TITLE
Minimized Version of >r

### ISSUE THREAD

**Issue by NotDarkkkk** [YoruNoKen/HanamiBot#103]
a setting to disable beatmap info and background on >r

**Comment by YoruNoKen** [comment]
![image](https://github.com/YoruNoKen/HanamiBot/assets/69751661/0a54f771-b7b1-46cf-a223-dd46e3da4dcd)
will be configurable in `/config` command

**Comment by YoruNoKen** [comment]
implemented in branch [rewrite](https://github.com/YoruNoKen/HanamiBot/tree/rewrite) in commit 74d590d
![image](https://github.com/YoruNoKen/HanamiBot/assets/69751661/404e3828-81fe-4179-9657-5d59dfc49cf5)
