### ISSUE TITLE
Hanami Roadmap

### ISSUE THREAD

**Issue by YoruNoKen** [YoruNoKen/HanamiBot#107]
Hello, this is a roadmap I made to monitor what needs to be changed/added to the bot. If you have any suggestions, please open an [issue](https://github.com/YoruNoKen/HanamiBot/issues/new/choose)!

## Upgrades
- [x] #153

## Commands
- [ ] #97 
- [x] #109 
- [x] #110 
- [ ] #114 
- [ ] #128
- [x] #126
- [ ] #135
- [ ] #136
- [ ] #137  
- [ ] #140
- [x] #146
- [ ] #151
- [ ] #154
- [ ] #160

## Features / Enhancements
- [x] #113 
- [x] #116
- [x] #123 
- [x] #131
- [ ] #139
- [ ] #141
- [x] #142
- [x] #144
- [x] #149
- [ ] #150
- [x] #161
- [ ] #164

## Bugs
- [x] #115 
- [x] #121 
- [ ] #124
- [x] #127
- [x] #133
- [x] #134
- [x] #138
- [x] #147
- [x] #148
- [x] #158
- [x] #165

**Comment by Radmos727** [comment]
big booty latina command

**Comment by YoruNoKen** [comment]
> big booty latina command

tf would that even do

**Comment by SandroMeow** [comment]
> > big booty latina command
> 
> 
> 
> tf would that even do

ight so like u take uhh reddit api for r/latinas and r/latinasGW and it posts latina women like random from top voted this momth maybe or week

**Comment by AtomikOverdrive** [comment]
command that shows you what skillset is weighted most for your top plays. maybe even shows the percentages on how it is weighted

**Comment by YoruNoKen** [comment]
what do you think the command should be called? @AtomikOverdrive

**Comment by AtomikOverdrive** [comment]
maybe like !skillset or !skillweight

**Comment by YoruNoKen** [comment]
`skills` sounds good

**Comment by YoruNoKen** [comment]
also, I would appreciate it if you opened a [new issue](https://github.com/YoruNoKen/HanamiBot/issues/new/choose) instead of talking here!

**Comment by AtomikOverdrive** [comment]
oh mb, have no clue how github works

**Comment by YoruNoKen** [comment]
Moved this to https://github.com/users/YoruNoKen/projects/3
