### ISSUE TITLE
mog command

### ISSUE THREAD

**Issue by Radmos727** [YoruNoKen/HanamiBot#117]
>MOG RADMOS_

**Comment by YoruNoKen** [comment]
I assume this would just be an alias for the `compare` command?

**Comment by Radmos727** [comment]
> I assume this would just be an alias for the `compare` command?

you would be correct, one line of code

**Comment by YoruNoKen** [comment]
you should open a PR for it :)

**Comment by YoruNoKen** [comment]
it's fine, go to `src/message-commands/compare.ts` and add a new string to array: `aliases` and you're good to go

**Comment by Radmos727** [comment]
soon....https://github.com/YoruNoKen/HanamiBot/assets/127623330/e47438ba-8893-4dc1-beae-b76ab988f170
